### PR TITLE
Create 2024-06-03.md

### PR DESCRIPTION
**Pull request by RachL**
Creating our meeting notes structure and first file.

context : we want to be more transparent about our meetings notes / link with the board. Here is a first experimentation

### CODE REVIEW

**Comment by lecoqlibre** [comment]
Thanks @RachL. We did also talk about the WebId topic. Should not it be part of the document?

**Review by lecoqlibre — COMMENTED** [review]
Thanks @RachL. We did also talk about the WebId topic. Should not it be part of the document?

**Comment by RachL** [comment]
@lecoqlibre yes feel free to add it. I thought everything was written in the dedicated issue, but maybe not!

**Comment by lecoqlibre** [comment]
> @lecoqlibre yes feel free to add it. I thought everything was written in the dedicated issue, but maybe not!

The meeting notes state:
> Notes are still useful for:
> - publish / be transparent on which topic people talked

So I was thinking that even if we don't detail the topic, it should be listed in the meeting notes.

**Review by RaggedStaff — APPROVED** [review]

**Review by lecoqlibre — APPROVED** [review]

**Review by RaggedStaff — APPROVED** [review]
:rocket: LGTM!

**Pull request merged**
