### PR TITLE
Clarified VOCbench Export Process

### LINKED ISSUE #19: Clarify VOCbench export process
Must include SKOS model & check "Include Inferred"

- [ ] Update gitbook to reflect this.

### PR DESCRIPTION
**Pull request by RaggedStaff**
Amended Taxonomy Update process to clarify that SKOS graph must be included to allow SKOS relationships to be inferred.

Closes #19

### CODE REVIEW

**Comment by RaggedStaff** [comment]
This seems to also include the decision around transmission of inverse relationships, I thought we already merged that. :confused:

**Comment by RachL** [comment]
Btw @RaggedStaff I'm not sure I can review here (and sorry it took me so long to see my review was required here 😱 )

**Comment by RachL** [comment]
@RaggedStaff what should we do with this PR?

**Comment by RaggedStaff** [comment]
Ping @Alcoz @lecoqlibre 

We still need to review/merge this PR.

**Review by lecoqlibre — APPROVED** [review]

**Comment by RaggedStaff** [comment]
@simonLouvet This was a change you requested, would you mind reviewing please?

**Review by Alcoz — APPROVED** [review]

**Pull request merged**
